### Join Now - Step 1
POST http://localhost/emailAuth/initRegister
content-type: application/json

{
    "name" : "Sachin Kumar",
    "email" : "sinha2abc@gmail.com",
    "password" : "HelloUser@123",
    "gender" : "M",
    "dob" : "2020-07-12",
    "isMinor" : false
}


### Join Now - Step 2 - Verify using URL - Register - Join Now - On Success redirect to dashboard
GET http://localhost/emailAuth/register/sinha2abc@gmail.com/11c56923-13f8-49aa-94ba-4dc1840e84a5


### Forgot Password - Step 1
POST http://localhost/emailAuth/forgotPswd
content-type: application/json

{
    "email": "sinha1abc@gmail.com"
}


### Forgot Password - Step 2 - Link Verification - On Success redirect to create password page
GET http://localhost/emailAuth/resetpswd/sinha2abc@gmail.com/11c56923-13f8-49aa-94ba-4dc1840e84a5


### Forgot Password - Step 3 - Along with Link Verification - On Success redirect dashboard
POST http://localhost/emailAuth/resetPswd
content-type: application/json

{
    "email": "shredtest1@gmail.com",
    "mailUID":"8a80e9bc-4e00-4d53-a0fe-c8f4010438fc",
    "password": "userAa@123"
}



### Login using Email and Password
POST http://localhost/emailAuth/login
content-type: application/json

{
    "email": "sinha1abc@gmail.com",
    "password": "S#i1lf54"
}
